const tutorData = {
  0: {
    0: "jjj jjj jjj jjj kkk kkk kkk kkk jjj kkk jjj kkk jjk j k k j j k k j jkj jjk kjj kkj jkk kkk jjj kjk",
    1: "lll lll lll lll ;;; ;;; ;;; ;;; lll ;;; lll ;;; ll; l ; ; l l ; ; l l;l ll; ;ll ;;l l;; ;;; lll ;l;",
    2: "jjj jjj kkk kkk jjj kkk lll lll ;;; ;;; lll ;;; jjl jj jk jl j; kj kk kl k; lj lk ll l; ;j ;k ;l ;;",
    3: "fff fff fff fff ddd ddd ddd ddd fff ddd fff ddd ffd f d d f f d d f fdf ffd dff ddf fdd ddd fff dfd",
    4: "sss sss sss sss aaa aaa aaa aaa sss aaa sss aaa ssa a a s a a s s a a s sas ssa aas saa aaa sss asa",
    5: "fff fff ddd ddd fff ddd sss sss aaa aaa sss aaa ffs ff fd fs fa df dd ds da sf sd ss sa af ad as aa",
    6: "jjj fff jjj fff jjj fff kkk ddd kkk ddd kkk ddd ll; fdf fdf fdf dfd dfd dfd sas sas sas asa asa asa",
    7: "hhh hhh hhh hhh ggg ggg ggg ggg hhh ggg hhh ggg hhg h g g h h g g h hgh hhg ghh ggh hgg ggg hhh ghg",
    8: "hhh hhh ggg ggg hhh ggg jjj jjj fff fff jjj fff hhj hh hg hj hf gh gg gj gf jh jg jj jf fh fg fj ff",
    9: "aaa aaa aaa ;;; ;;; ;;; sss sss sss lll lll lll ddh hah hah a l s j d h g ; f k l f s ; j g k h a d",
  },
  1: {
    0: "uuu uuu uuu uuu rrr rrr rrr rrr uuu rrr uuu rrr uur u r r u u r r u uru uur ruu rru urr rrr uuu rur",
    1: "uuu uuu rrr rrr uuu rrr jjj uuu jjj uuu fff rrr fff gug gug huh huh juj juj kuk kuk lul lul ;u; ;u;",
    2: "iii iii iii iii eee eee eee eee iii eee iii eee iie i e e i i e e i iei iie eii eei iee eee iii eie",
    3: "iii iii eee eee iii eee kkk iii kkk iii ddd eee ddf gig gig hih hih jij jij kik kik lil lil ;i; ;i;",
    4: "kid red did rid fed riff kidder udder rudder sir i shares slur skids kisses fuss gassed hags haggle",
    5: "ooo ooo ooo ooo www www www www ooo www ooo www oow o w w o o w w o owo oow woo wwo oww www ooo wow",
    6: "ooo ooo www www ooo www lll ooo lll ooo sss www ssf gog gog hoh hoh joj joj kok kok lol lol ;o; ;o;",
    7: "ppp ppp ppp ppp qqq qqq qqq qqq ppp qqq ppp qqq ppq p q q p p q q p pqp ppq qpp qqp pqq qqq ppp qpq",
    8: "ppp ppp qqq qqq ppp qqq ;;; ppp ;;; ppp aaa qqq aaf gpg gpg hph hph jpj jpj kpk kpk lpl lpl ;p; ;p;",
    9: "yyy yyy yyy yyy ttt ttt ttt ttt yyy ttt yyy ttt yyt y t t y y t t y yty yyt tyy tty ytt ttt yyy tyt",
    10: "yyy yyy ttt ttt yyy ttt ;;; yyy ;;; yyy aaa ttt aaf gyg gyg hyh hyh jyj jyj kyk kyk lyl lyl ;y; ;y;",
  },
  2: {
    0: "mmm mmm mmm mmm vvv vvv vvv vvv mmm vvv mmm vvv mmv m v v m m v v m mvm mmv vmm vvm mvv vvv mmm vmv",
    1: "mmm mmm vvv vvv mmm vvv jjj mmm jjj mmm fff vvv fff gmg gmg hmh hmh jmj jmj kmk kmk lml lml ;m; ;m;",
    2: ",,, ,,, ,,, ,,, ccc ccc ccc ccc ,,, ccc ,,, ccc ,,c , c c , , c c , ,c, ,,c c,, cc, ,cc ccc ,,, c,c",
    3: ",,, ,,, ccc ccc ,,, ccc kkk ,,, kkk ,,, ddd ccc ddf g,g g,g h,h h,h j,j j,j k,k k,k l,l l,l ;,; ;,;",
    4: "... ... ... ... xxx xxx xxx xxx ... xxx ... xxx ..x . x x . . x x . .x. ..x x.. xx. .xx xxx ... x.x",
    5: "... ... xxx xxx ... xxx lll ... lll ... sss xxx ssf g.g g.g h.h h.h j.j j.j k.k k.k l.l l.l ;.; ;.;",
    6: "/// /// /// /// zzz zzz zzz zzz /// zzz /// zzz //z / z z / / z z / /z/ //z z// zz/ /zz zzz /// z/z",
    7: "/// /// zzz zzz /// zzz ;;; /// ;;; /// aaa zzz aaf g/g g/g h/h h/h j/j j/j k/k k/k l/l l/l ;/; ;/;",
    8: "nnn nnn nnn nnn bbb bbb bbb bbb nnn bbb nnn bbb nnb n b b n n b b n nbn nnb bnn bbn nbb bbb nnn bnb",
    9: "nnn nnn bbb bbb nnn bbb ;;; nnn ;;; nnn aaa bbb aaf gng gng hnh hnh jnj jnj knk knk lnl lnl ;n; ;n;",
  },
  3: {
    0: "777 777 777 777 888 888 888 888 j7j j7j j7j k8k k8 87 87 87 j7j j7j k8k k8k 777 777 777 888 888 888",
    1: "999 999 999 999 000 000 000 000 l9l l9l l9l ;0; ;0 09 09 09 l9l l9l ;0; ;0; 999 999 999 000 000 000",
    2: "444 444 444 444 333 333 333 333 f4f f4f f4f d3d d3 34 34 34 f4f f4f d3d d3d 444 444 444 333 333 333",
    3: "222 222 222 222 111 111 111 111 s2s s2s s2s a1a a1 12 12 12 s2s s2s a1a a1a 222 222 222 111 111 111",
    4: "555 555 555 555 666 666 666 666 f5f f5f f5f f5f f6 65 65 65 f5f f5f f6f f6f 555 555 555 666 666 666",
    5: "111 111 111 222 222 222 333 333 333 444 444 444 551.09 8.23 74.56 6.32 98.1 -403.78 45/7 -.9999 / 3",
  },
};
